//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bellcast.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Crop> Crops { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<DiseaseForecast> DiseaseForecasts { get; set; }
        public virtual DbSet<Humidity> Humidities { get; set; }
        public virtual DbSet<LeafWetnessDuration> LeafWetnessDurations { get; set; }
        public virtual DbSet<Pathogen> Pathogens { get; set; }
        public virtual DbSet<RiskLevel> RiskLevels { get; set; }
        public virtual DbSet<Temperature> Temperatures { get; set; }
        public virtual DbSet<Weather> Weathers { get; set; }
    }
}
