//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bellcast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int cityId { get; set; }
        public double lon { get; set; }
        public double lan { get; set; }
        public string name { get; set; }
    }
}
