//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bellcast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeafWetnessDuration
    {
        public bool value { get; set; }
        public int dateTime { get; set; }
        public int cityId { get; set; }
    }
}
